# Generated by Django 4.1.2 on 2022-10-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='alt',
            field=models.TextField(default='', max_length=2000, verbose_name='alt'),
        ),
        migrations.AddField(
            model_name='media',
            name='height',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Altura da imagem'),
        ),
        migrations.AddField(
            model_name='media',
            name='width',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Largura da imagem'),
        ),
    ]
