# Generated by Django 4.1.2 on 2022-10-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_media_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='document',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
